### ISSUE TITLE
Clarify installation process / requirements

### ISSUE THREAD

**Issue by rbrlortie** [absolunet/nwayo#19]
Installation process is not very clear. Project requirements should be more precise. 

It is not very clear that the user needs to install GraphicsMagick and / or ImageMagick manually and which versions are required. This is especially true until issue #17 is resolved.

Suggestion: Outline installation process in details and point the user towards Homebrew or Chocolatey to manage requirements.

**Comment by rbrlortie** [comment]
Download and install Chocolatey
**https://chocolatey.org/install**

**choco install nodejs**
**choco install bower**

**choco install graphicsmagick**
**choco install imagemagick.app -PackageParameters LegacySupport=true**
**choco install imagemagick -PackageParameters LegacySupport=true**

**choco install ruby
gem update --system
gem install sass
gem install compass
gem install scss_lint**
(If SSL errors when using gem command, fix them or use : 
**gem sources --remove https://rubygems.org/
gem sources --add http://rubygems.org/**
to use the non HTTPS version. Not recommended due to security issues.)

(In nwayo folder:)

(Replace MYPROJECT in bower.json and package.json with your project's name
Rename MYPROJECT.sublime-project with your project's name)

**npm install
bower install**

**nwayo rebuild**

~ enjoy ~

**Comment by jblandry** [comment]
https://github.com/absolunet/nwayo/tree/master/docs/install
