### ISSUE TITLE
Génération du favicon.ico sur PC problématique

### ISSUE THREAD

**Issue by leandreb** [absolunet/nwayo#2]
Lors d'un rebuild, le fichier favicon.ico et parfois généré dans un endroit erroné :
- nwayo/build/**icons/bundlename**/favicon.ico

deviens parfois
- nwayo/build/**undefined**/favicon.ico

**Comment by mkrimi** [comment]
Justement, hier one s'est demandé, pourquoi dans le cas de Magento on
n'utilise pas le favicon fourni dans l'admin de Magento ? Y-a t-il un réel
gain de passer par nwayo ? est-ce liée à l'encodage ?

Merci.

_Cordialement,​_

_Mohamed Krimi_

Chef d'équipe développement

---

_Absolunet inc._
4398, Boulevard Saint-Laurent, bur.204
Montréal (Québec)
H2W 1Z5

Téléphone: 450.979.7620 x314
Sans frais: 1.877.979.2276
Télécopieur: 888.563.3057

www.absolunet.com

Vous pouvez aussi nous suivre sur Twitter http://twitter.com/Absolunet et
Facebook
http://www.facebook.com/home.php#/pages/Boisbriand-QC/Absolunet/79656927026?ref=ts

2015-12-10 9:58 GMT-05:00 Léandre Brière notifications@github.com:

**Comment by jblandry** [comment]
Le nwayo génère un favicon.ico qui contient plusieurs grandeurs spécifique. (ref: https://github.com/absolunet/nwayo/blob/master/src/tasks/icons.coffee#L25)

**Comment by jblandry** [comment]
Dans workflow/helpers/_util.js - assetsRename il faut gérer le split en considérant que sur Windows le séparateur est \

**Comment by jblandry** [comment]
Corrigé par le commit 0f02052fed0a9f8bf05243ecfb8d4e5014771585
