### ISSUE TITLE
Allow direct overrides for variables in konstan by bundles

### ISSUE THREAD

**Issue by fforget** [absolunet/nwayo#24]
Rather than creating a new variable (ex.: $konstan-current-color-bg) for the current bundle, directly override the default one (ex.: $konstan-color-bg).

This would prevent duplicates and errors when a specific variable is not redefined for a bundle when you actually want the default value.

**Comment by jblandry** [comment]
Obsolete via 45e71c010aa99a4bf59d0ff3cc57e3be64c064d6
