### ISSUE TITLE
Nwayo doctor CLI client version

### ISSUE THREAD

**Issue by mrobichaud-absolunet** [absolunet/nwayo#31]
Nwayo CLI latest version is 1.0.0 not 3.1.13

 CLI diagnosis
    You are a dull blade   ಠ_ಠ

    1.0.0 ➝  3.1.13

**Comment by jblandry** [comment]
Done via https://github.com/absolunet/nwayo-cli/commit/ff8cc094c84256079fdd8a60f928d05ec59cc8a3
