### ISSUE TITLE
folder.match() returns null on rebuild

### ISSUE THREAD

**Issue by thierry2015** [absolunet/nwayo#34]
During a nwayo rebuild:

`TypeError: Cannot read property 'Symbol(Symbol.iterator)' of null at bundles (C:\work\sites\iprospect\nwayo\node_modules\@absolunet\nwayo-workflow\workflow\helpers\env.js:53:28)`

**Comment by jblandry** [comment]
Réglé via c0f1e40982fdfdcf49b4ab87ce3f8ee586a70d4b
