### ISSUE TITLE
nwayo rebuild fails once every two times (3.5.0-beta.4 / windows)

### ISSUE THREAD

**Issue by fforget** [absolunet/nwayo#41]
Tested running version 3.5.0-beta.4 on Windows.
Call `nwayo rebuild` twice in a row to reproduce the error.

> C:\VSDEV\project\nwayo\node_modules\async-done\index.js:18
>     throw err;
>     ^
> 
> Error [ERR_UNHANDLED_ERROR]: Unhandled error. ([object Object])
>     at Gulp.emit (events.js:169:17)
>     at Gulp.emit (domain.js:421:20)
>     at Object.error (C:\VSDEV\project\nwayo\node_modules\undertaker\lib\helpers\createExtensions.js:61:10)
>     at handler (C:\VSDEV\project\nwayo\node_modules\now-and-later\lib\mapSeries.js:43:14)
>     at f (C:\VSDEV\project\nwayo\node_modules\once\once.js:25:25)
>     at f (C:\VSDEV\project\nwayo\node_modules\once\once.js:25:25)
>     at tryCatch (C:\VSDEV\project\nwayo\node_modules\async-done\index.js:24:15)
>     at done (C:\VSDEV\project\nwayo\node_modules\async-done\index.js:40:12)
>     at Domain.onError (C:\VSDEV\project\nwayo\node_modules\async-done\index.js:51:5)
>     at Object.onceWrapper (events.js:272:13)
>     at Domain.emit (events.js:180:13)
>     at Domain.emit (domain.js:421:20)
>     at Domain._errorHandler (domain.js:219:21)
>     at Object.setUncaughtExceptionCaptureCallback (domain.js:119:29)
>     at process._fatalException (bootstrap_node.js:430:31)

**Comment by jblandry** [comment]
Seems to be limited to the beta.4 only
