### ISSUE TITLE
Cssnano removes browser prefixes

### ISSUE THREAD

**Issue by rbrlortie** [absolunet/nwayo#43]
**Description**  
Cssnano has its own Autoprefixer. It uses it to remove uneeded browser prefixes.

Nwayo also has Autoprefixer. You can use it to target older browsers.

Cssnano's autoprefixer parse the CSS after nwayo's autoprefixer had added the prefixes. This means that the browser setting in the bundle's yaml is ignored.

**How to reproduce**  
- Configure Nwayo to add prefixes for `'iOS >= 8'` and use `flex: 1 1 0px;`
- Nwayo will add `-webkit-flex: 1 1 0px`
- Now run with minify set to true
- Cssnano removes `-webkit-flex: 1 1 0px`

**Possible Solution**  
- Solution 1: Disable cssnano's autoprefixer 
e.g. `cssnano({ autoprefixer:{false}})` 
- Solution 2: Pass array of browsers to cssnano's Autoprefixer
e.g. ` 				.pipe(gulpif(bundle.styles.options.minify && !ENV.watching, cssnano({ autoprefixer:{ browsers:bundle.styles.options.autoprefixer }, reduceIdents:false, zindex:false })))
 `

**Comment by rbrlortie** [comment]
Tested on 3.3.5 but it seems that cssnano was never updated in 3.5.0 so the issue should still be there.

**Comment by jblandry** [comment]
Corrected via 625332f648332d4d4c75f7ff7dcda80c65dd021f

**Comment by rbrlortie** [comment]
Is this merged into `master` / `3.5.2`? Is `release/next` stable to use?

**Comment by jblandry** [comment]
Is in `3.6.0-beta.3` onwards.
You should use tagged versions only not branches ;)

**Comment by rbrlortie** [comment]
Should one use the RC  `3.6.0-rc.4` or the Beta `3.6.0-beta.6` tags? In other words, are release candidates considered stable or only betas?

**Comment by rbrlortie** [comment]
@jblandry

Should one use the RC `3.6.0-rc.4` or the Beta `3.6.0-beta.6` tags? In other words, are release candidates considered stable or is it only betas that are stable?

**Comment by jblandry** [comment]
Alpha → Beta → Release Candidate → Stable

https://en.wikipedia.org/wiki/Software_release_life_cycle#Stages_of_development

**Comment by rbrlortie** [comment]
Thanks, wasn't sure which release cycle was used. 👍
