### ISSUE TITLE
Loading foundation-sites (6.x) utility from toolbox impact build that doesn't rely on Foundation 6

### ISSUE THREAD

**Issue by thierry2015** [absolunet/nwayo#46]
https://github.com/absolunet/nwayo/blob/09d76a14d3a7e6cc6518ccc77503241cac5145a5/toolbox/styles/_functions.scss#L6

Since rem-calc() is only used for 1px/-1px, is it still necessary to rely on this function?

**Comment by jblandry** [comment]
Corrected by 0ab37ceb46dc82fed38c19eb100f75fd6210fbe3
