### ISSUE TITLE
Handle no icons in assets components

### ISSUE THREAD

**Issue by thierry2015** [absolunet/nwayo#49]
As a developer, I want to be able to do a `nwayo rebuild` without any icons in my components to process in order to use the other functionalities with the same command.

Currently, rebuilding a bundle without any `/components/{name}/assets/icons/icon.png` file throws an error: `Error [ERR_STREAM_CANNOT_PIPE]: Cannot pipe, not readable`. In fact, not having any assets component in a YAML bundle file causes the issue (no item in the assets.components list, not having the assets.components defined in the file or not having a component with the `assets/icons/icon.png` file in the list)

To reproduce the issue:

1. Install the 3.6.0-rc.1 boilerplate, the workflow and the vendors
2. Remove the `site` component reference in the _main.yaml file of the bundle
3. Do a `nwayo rebuild` or a `nwayo run icons-icon`
4. The error should appear

**Comment by jblandry** [comment]
Corrected via 396c3ccd558e43008f2fb133ae8eddda4d229139
