### ISSUE TITLE
[BUG] Cannot install vendors

### ISSUE THREAD

**Issue by blchv** [absolunet/nwayo#57]
**Describe the bug**
```
user@user-VirtualBox:[...]/nwayo$ nwayo install vendors
[...]/nwayo/node_modules/@absolunet/nwayo-workflow/helpers/env.js:34
                        const scopedMatch = (/^(?<kebab1>@[a-z0-9-]+\/)(?<kebab2>[a-z0-9-]+)$/u).exec(name);
                                            ^

SyntaxError: Invalid regular expression: /^(?<kebab1>@[a-z0-9-]+\/)(?<kebab2>[a-z0-9-]+)$/: Invalid group
    at Object.keys.forEach ([...]/nwayo/node_modules/@absolunet/nwayo-workflow/helpers/env.js:34:24)
    at Array.forEach (<anonymous>)
    at EXTENSIONS ([...]/nwayo/node_modules/@absolunet/nwayo-workflow/helpers/env.js:30:39)
    at Object.<anonymous> ([...]/nwayo/node_modules/@absolunet/nwayo-workflow/helpers/env.js:60:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
```

**To Reproduce**
1. Provision Virtual Machine using
    - Distributor ID:	Ubuntu
    - Description:	Ubuntu 18.04.3 LTS
    - Release:	18.04
    - Codename:	bionic

2. Install Node.js, nwayo CLI, GraphicsMagick / ImageMagick

3. Follow the provided **Get Started** guite @ [https://github.com/absolunet/nwayo](https://github.com/absolunet/nwayo)

**Expected behavior**
To install vendors.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.3 LTS

**Additional context**
You'll probably need more information. Just let me know and I'll update the issue.

**Comment by blchv** [comment]
2 weeks later and with 0 feedback from the team, it seems that nwayo is abandoned and no longer maintained.

Please correct me if I'm wrong. Cheers!

**Comment by jblandry** [comment]
Sorry @vankama our bad... 
Our open-source reflexes are not there yet. 

Could you tell me your Node.js version, npm version, nwayo cli and nwayo workflow version ?  (nwayo versions are available if you call `nwayo` in your terminal under your project's nwayo folder).

Thanks and again sorry for the delay.

**Comment by jblandry** [comment]
Hey @vankama is this still an issue or should we close it?

**Comment by admiralbob77** [comment]
I can't get this to work either. Errors out with a "Missing write access to /home/[username]/nwayo/vendor" helpfully suggesting "try sudo", and then when you do use sudo, gives a cutesey message saying "It is useless to force me with a sudo"

**Comment by jblandry** [comment]
Hey @admiralbob77, could you tell me your Node.js version, npm version, nwayo cli and nwayo workflow version ? (nwayo versions are available if you call `nwayo` in your terminal under your project's nwayo folder).

**Comment by jblandry** [comment]
@admiralbob77 after re-reading your comment, it doesn't seem to be the same issue as @vankama at all. 

In your case the nwayo cli basically runs a `npm install` under the `vendor` directory with the current user. If this user doesn't have access then nwayo won't access as well. 

Since you are developing in this directory, normally your current user should have access or else development would be complicated, that's why nwayo forbids an excessive use of `sudo`.

It really seems to be a permission problem more than a nwayo problem. Please follow up if the issue persists after correcting your permissions.
