### ISSUE TITLE
install workflow doesn't work

### ISSUE THREAD

**Issue by admiralbob77** [absolunet/nwayo#58]
It chokes on adding node-sass and won't complete. Successful workaround: do npm config set unsafe-perm true first. 

Your install scripts should specify this for all the packages it adds.

**Comment by jblandry** [comment]
Thanks for your feedback. 

By default the `unsafe-perm` config is true unless it is run by the root user (https://docs.npmjs.com/misc/config#unsafe-perm), so we will not force a change of npm's default behavior for an edge case by, I'm assuming since you're running as root, a power user.
